version: '3.9'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: DATABASE
      POSTGRES_DB: food_delivery_db
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  restaurant-user-service:
    build: ./restaurant-user-service
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: DATABASE
      DB_NAME: food_delivery_db

  user-service:
    build: ./user-service
    ports:
      - '3001:3001'
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: DATABASE
      DB_NAME: food_delivery_db

  delivery-agent-service:
    build: ./delivery-agent-service
    ports:
      - '3002:3002'
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: DATABASE
      DB_NAME: food_delivery_db

volumes:
  pgdata:
