services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: food_delivery_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: DATABASE
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  user-service:
    build: ./user-service
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: DATABASE
      DB_NAME: food_delivery_db
      PORT: 3001

  restaurant-user-service:
    build: ./restaurant-user-service
    ports:
      - "3002:3002"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: DATABASE
      DB_NAME: food_delivery_db
      PORT: 3002

  delivery-agent-service:
    build: ./delivery-agent-service
    ports:
      - "3003:3003"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: DATABASE
      DB_NAME: food_delivery_db
      PORT: 3003

volumes:
  postgres_data:
